apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-rabbitmq-controller
subjects:
  - kind: ServiceAccount
    name: rabbitmq-controller-manager
    namespace: knative-sources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-sources-rabbitmq-controller